### ISSUE TITLE
packge not working correctly 

### ISSUE THREAD

**Issue by maiq9** [PixelRocket-Shop/sigma#5]
Hello, there is an error in css compile files libs.scss & theme.scss

ERROR in ./src/assets/scss/libs.scss
Package subpath './package.json' is not defined by "exports" in I:\Design+UI\Templates\UI\sigma-main\node_modules\postcss\package.json

It may need postcss configuration or something like that ...  , can you please help with that !

Thank you

**Comment by pixelrocket66** [comment]
Hey, I'm in the processing of updating all the packages, including the build process. So I'm not going to debug this current version. Will be releasing V2 of the theme soon.

**Comment by mathew2005** [comment]
when will you launch the v2 of the theme? I genuinely give it to you. This is really impressive free or not.

**Comment by criketman66** [comment]
Good morning,



I’m in the process of updating my existing templates and also creating a new range of templates. I can’t give you an exact date for Sigma’s update – I’m first going to release the new templates. But I would think I will have updated Sigma to the latest Bootstrap (and also created a Tailwind version) in about a month, maybe two months time.


Rob

From: mathew2005 ***@***.***>
Date: Friday, 3 May 2024 at 21:33
To: PixelRocket-Shop/sigma ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [PixelRocket-Shop/sigma] packge not working correctly (Issue #5)

when will you launch the v2 of the theme? I genuinely give it to you. This is really impressive free or not.
